### ISSUE TITLE
[Feat] 希望新增一个接口，判断某个直播间是否在直播中

### ISSUE THREAD

**Issue by biggerxiong** [iyear/pure-live-core#16]
现在有收藏功能，可以让用户收藏某个直播间。

但是用户无法直观地看到哪个直播间正在播，想看收藏的主播还得一个一个点进去看。

希望增加一个判断直播间是否开播的接口，用于在收藏界面显示该主播直播状态（直播中/未直播）

**Comment by biggerxiong** [comment]
看到代码中 `GetRoomInfo` 已有房间的状态信息，那么就只需要在前端添加 **直播中** 显示即可。

**Comment by iyear** [comment]
添加批量查询房间状态接口
