### ISSUE TITLE
[Feat] 使用斗鱼公共 api 替换内部服务

### ISSUE THREAD

**Issue by biggerxiong** [iyear/pure-live-core#24]
现在斗鱼直播间获取 roomInfo 的接口是通过解析 "https://m.douyu.com/%s" 来获取房间信息的

是否考虑用斗鱼公共 api 来替换这个操作？

相关信息：

https://github.com/yyc-dev/douyu-sdk/blob/master/斗鱼第三方开放平台API文档v2.2.pdf

https://www.cnblogs.com/jiaoxiangjie/p/6748039.html

其他开源项目中也有使用这些 api ，如 https://github.com/guyijie1211/JustLive-Api

**Comment by iyear** [comment]
可以的，使用官方提供的API更好一些，更优雅。后续的搜索和推荐似乎也可以用
