### ISSUE TITLE
[BUG]说起来大佬你可能不信，01.0版本的static前端，有点问题

### ISSUE THREAD

**Issue by VantIer** [iyear/pure-live-core#25]
版本：v0.1.0-release
系统环境：树莓派 Zero 2 W
错误反应：
    程序本身无任何报错，但是执行后登录网页，网页不能加载直播间（例如选择平台输入直播间号后加载，加载不出直播也不会有未开播提示），同时收藏页也显示为空（我一开始发现的就是收藏空了，检查配置文件无问题数据库无问题）
    用旧版发布的static替换后一切恢复正常。

另外想问一句，现在斗鱼下载流关闭的逻辑是写在了刷新上吗，。我直接切换直播间看下载流还有，但是刷新就没了（这条不是bug
，就是确认下，好培养操作习惯）

**Comment by iyear** [comment]
v0.1.0-release windows 64bit 二进制部署三个平台均无法复现无法直播的问题。

目前的前端防止后台拉流实现是，每次切换直播间都刷新当前页面

关于后台依旧拉流的问题，core是正常实现的，但是前端的flvjs本身存在bug，https://github.com/bilibili/flv.js/pull/448，flvjs最新版本仍然无法解决此问题，只能借刷新关闭拉流

**Comment by VantIer** [comment]
> v0.1.0-release windows 64bit 二进制部署三个平台均无法复现无法直播的问题，能否尝试别的平台是否存在同样的问题。收藏页也无法复现
> 
> 目前的前端防止后台拉流实现是，每次切换直播间都刷新当前页面
> 
> 关于后台依旧拉流的问题，core是正常实现的，但是前端的flvjs本身存在bug，[bilibili/flv.js#448](https://github.com/bilibili/flv.js/pull/448) ， flvjs最新版本仍然无法解决此问题，只能借刷新关闭拉流
> 
> 前端我不太会临时糊的，等大佬能接手前端

收到！感谢大佬，那我自己再研究研究，改改前端！

**Comment by iyear** [comment]
好像呼吁呀复现了

> > v0.1.0-release windows 64bit 二进制部署三个平台均无法复现无法直播的问题，能否尝试别的平台是否存在同样的问题。收藏页也无法复现
> > 目前的前端防止后台拉流实现是，每次切换直播间都刷新当前页面
> > 关于后台依旧拉流的问题，core是正常实现的，但是前端的flvjs本身存在bug，[bilibili/flv.js#448](https://github.com/bilibili/flv.js/pull/448) ， flvjs最新版本仍然无法解决此问题，只能借刷新关闭拉流
> > 前端我不太会临时糊的，等大佬能接手前端
> 
> 收到！感谢大佬，那我自己再研究研究，改改前端！

旧版前端是没有切换刷新实现的，如果不想后台拉流只能手动刷新

**Comment by VantIer** [comment]
> > > v0.1.0-release windows 64bit 二进制部署三个平台均无法复现无法直播的问题，能否尝试别的平台是否存在同样的问题。收藏页也无法复现
> > > 目前的前端防止后台拉流实现是，每次切换直播间都刷新当前页面
> > > 关于后台依旧拉流的问题，core是正常实现的，但是前端的flvjs本身存在bug，[bilibili/flv.js#448](https://github.com/bilibili/flv.js/pull/448) ， flvjs最新版本仍然无法解决此问题，只能借刷新关闭拉流
> > > 前端我不太会临时糊的，等大佬能接手前端
> > 
> > 
> > 收到！感谢大佬，那我自己再研究研究，改改前端！
> 
> 旧版前端是没有切换刷新实现的，如果不想后台拉流只能手动刷新

明白了~
另外我在我这里反复实验，确实可以复现新版前端加载不出收藏夹这个问题，而且电脑、手机多个浏览器均如此（中间发现有缓存影响，每次实验均清空浏览器缓存）。奇了怪了。您这里复现不了的话就不好说是啥问题了，也许是我个人的设备问题。那我就先把这个bug关闭了，不算bug。要是以后还有兄弟出现这问题再说。

**Comment by iyear** [comment]
arm64 二进制部署复现

**Comment by iyear** [comment]
细节的问题，release的前端是手动打包的，把本地调试写死的ip和端口打包进去了，将重新上传修复后的打包文件

**Comment by iyear** [comment]
已重新上传，现在的v0.1.0-release已经可以正常使用

**Comment by iyear** [comment]
还是有问题，本地可以了上传以后又不行了

**Comment by iyear** [comment]
由于github应该是有release的上传缓存策略，本地新的打包上传以后下载还是旧的，现在开了一个新的release。已经正常。

https://github.com/iyear/pure-live-core/releases/tag/v0.1.0-release_fix

**Comment by VantIer** [comment]
> 由于github应该是有release的上传缓存策略，本地新的打包上传以后下载还是旧的，现在开了一个新的release。已经正常。
> 
> https://github.com/iyear/pure-live-core/releases/tag/v0.1.0-release_fix

收到！感谢大佬！
