### ISSUE TITLE
直播间是否开启探测的潜在问题-后续请求被拒绝

### ISSUE THREAD

**Issue by VantIer** [iyear/pure-live-core#28]
大佬你好，又是我！真是不好意思(^～^;)ゞ
发现一个新功能_直播间是否开启 及相应的播放键蓝色显示的问题。貌似出在了探测上。
就是第一次打开收藏夹都是正常的，但是后续再打开（不一定是第二次，有可能几次后），就会出现收藏夹显示不了的问题。（如果在收藏夹页面刷新大概率出问题）
经过检查，貌似是b站探测的问题，探测太多好像会被ban（貌似是ban账号），需要一段时间冷却后才会恢复，才能重新探测到直播信息。被ban适合提示请求被拦截412，如图
（这个是网页被ban后使用指令的效果，可以看到douyu是ok的，b站不行，10分钟后就好了）
[DSC_0026.JPG](https://user-images.githubusercontent.com/44759505/149338991-41d8fb3f-4fd4-4777-910b-d664804eef39.JPG)

这个不是咱的bug，但确实有时候影响使用。

貌似是我D的太多了？(｡ﾉω＼｡)
我用旧版前端了，随便刷新无此问题。

这不是个bug哦，算是反馈个情况，大佬看完可以直接关闭，相关情况写个readme提醒下大概就ok了

**Comment by iyear** [comment]
考虑后续采用缓存机制保存重复访问的问题

**Comment by biggerxiong** [comment]
> 考虑后续采用缓存机制保存重复访问的问题

这个项目直接用 sqlite 数据库做缓存就 ok 了吧，保持轻量级

**Comment by iyear** [comment]
> > 考虑后续采用缓存机制保存重复访问的问题
> 
> 这个项目直接用 sqlite 数据库做缓存就 ok 了吧，保持轻量级

用go-cache存内存可以直接设expiration，sqlite还要自己维护超时。但是会增加内存占用

**Comment by iyear** [comment]
v0.1.2已发布，解决了该问题
