### ISSUE TITLE
请问收藏夹存在哪个文件，更新的时候覆盖没了

### ISSUE THREAD

**Issue by Pulut** [iyear/pure-live-core#29]
请问收藏夹存在哪个文件，更新的时候覆盖没了，下载新版覆盖，直接给弄没了，下次我备份一下

**Comment by biggerxiong** [comment]
收藏存在 `data` 这个文件夹里，里面有一个 `data.db` ，这是收藏存的数据库文件

**Comment by Pulut** [comment]
> 收藏存在 `data` 这个文件夹里，里面有一个 `data.db` ，这是收藏存的数据库文件

看到了，谢谢，下次不覆盖这个了。另外，能不能弄个qq或者微信群，方便沟通

**Comment by iyear** [comment]
README中有备份数据库的命令

**Comment by iyear** [comment]
> > 收藏存在 `data` 这个文件夹里，里面有一个 `data.db` ，这是收藏存的数据库文件
> 
> 看到了，谢谢，下次不覆盖这个了。另外，能不能弄个qq或者微信群，方便沟通

目前不考虑建立交流群，否则很多问题都在群里问，很不方便追踪和引用
