### ISSUE TITLE
关于收藏夹两点意见

### ISSUE THREAD

**Issue by Pulut** [iyear/pure-live-core#33]
1.建议收藏夹默认按照开播状态排序，开播的排在前面
2.建议点击收藏夹，不用刷新，查询是否开播，而是加一个刷新按钮，用来查询该收藏夹里的主播是否开播。目前这样，我看一个主播 ，想切换另外一个，从播放页面切回到收藏夹，收藏夹就会去刷新，很费时间和资源，没太大必要每次都刷新。

**Comment by iyear** [comment]
这块属于前端的问题
1. 这个我尝试通过筛选按钮来增加功能，原功能保持不变
2. 后端最新commit采用了缓存策略 #28 ，第一次请求完都是缓存，缓存时间为1min，后续也可考虑定时任务后台刷新，请等待新版本

**Comment by iyear** [comment]
v0.1.2已发布，解决了该问题
