### ISSUE TITLE
[斗鱼直播无效] 说出来都没人信

### ISSUE THREAD

**Issue by yukminnie** [iyear/pure-live-core#40]
软件平台： windows， linux（docker版）
时间：2022-05-20
直播平台： 斗鱼

失效直播间例子：[洞庭湖](https://www.douyu.com/138243)

ps: 其他平台正常（比心

**Comment by yukminnie** [comment]
尝试复制直播流地址，uuid为空

```
http://dyscdnali1.douyucdn.cn/live/138243rMdUNsh3Qs.flv?uuid=
```

**Comment by iyear** [comment]
@yukminnie uuid为空是正常情况，本来就为空。斗鱼地址失效是因为CDN改变了。在 https://github.com/iyear/pure-live-core/commit/0808226bc859334bf2b2d037aa9487f0df064088 中修复了此问题，但是没有发布新版本。今天考虑发布新的fix版本，感谢您的反馈！

**Comment by iyear** [comment]
V0.1.3 已发布
