### ISSUE TITLE
[BUG] 斗鱼CDN失效

### ISSUE THREAD

**Issue by xyf2018** [iyear/pure-live-core#45]
pure-live-core 0.1.3版本
vplay1a.douyucdn.cn CDN已失效

目前可用CDN
akm-tct.douyucdn.cn
后缀不变

**Comment by junlinwu3** [comment]
作者fix之前可以用着这个先，我fork了用github action build的
https://hub.docker.com/r/junlinwu/pure-live/

**Comment by iyear** [comment]
@xyf2018 目前仍然可用吗

**Comment by xyf2018** [comment]
@iyear 目前可用

**Comment by loverubywithout** [comment]
建议可以config中可以自己指定CDN，这样就不用每次都重新打包或者fix了

**Comment by iyear** [comment]
年久失修，我先把CI跑起来，近期做一些重构更新

**Comment by iyear** [comment]
https://github.com/iyear/pure-live-core/releases/tag/v0.1.4 已修复该问题
