### ISSUE TITLE
请教两个问题 

### ISSUE THREAD

**Issue by Pulut** [iyear/pure-live-core#6]
1. 清晰度似乎不是最高的，对比同类型的justlive，同一个主播，清晰度有一定差距
2. 我用电脑ssh连群晖，运行，再用电脑浏览器，是可以连群晖的服务正常观看的，但是我关了电脑的ssh窗口，服务就停止了，请问需要在群晖上怎么设置，它才能一直在运行

十分感谢作者做出这么好的东西

**Comment by iyear** [comment]
清晰度不够得是哪个平台

后台运行可以以下三选一，网上搜一下教程很多
1. &
2. screen
3. nohop

**Comment by Pulut** [comment]
虎牙的，

**Comment by iyear** [comment]
> 虎牙的，

正式版会尝试修复这个问题

**Comment by Pulut** [comment]
> > 虎牙的，
> 
> 正式版会尝试修复这个问题，测试中我也有这个感觉

还有个问题，我的显示器是27寸，2560*1440分辨率，用浏览器看的时候，上下显示不全，能不能做成自适应

**Comment by iyear** [comment]
> > > 虎牙的，
> > 
> > 
> > 正式版会尝试修复这个问题，测试中我也有这个感觉
> 
> 还有个问题，我的显示器是27寸，2560*1440分辨率，用浏览器看的时候，上下显示不全，能不能做成自适应

这个是前端问题，现在前端写的太烂了，自适应都还没做，只是个展示demo，等正式版我完善

**Comment by VantIer** [comment]
> 1. 清晰度似乎不是最高的，对比同类型的justlive，同一个主播，清晰度有一定差距
> 2. 我用电脑ssh连群晖，运行，再用电脑浏览器，是可以连群晖的服务正常观看的，但是我关了电脑的ssh窗口，服务就停止了，请问需要在群晖上怎么设置，它才能一直在运行
> 
> 十分感谢作者做出这么好的东西

nohup ./pure-live .....   &，然后再输disown，就可以关闭终端了，会转交给根进程
